### ISSUE TITLE
Bundle.entry resource not fully expanding

### ISSUE THREAD

**Issue by hsolbrig** [fhircat/org.hl7.fhir.core#1]
http://build.fhir.org/bundle.html has a `BackBoneElement` named `entry`, which consists of
 - link
 - fullUrl
 - resource
 - search
 - request
 - response

link, search, request and response aren't in https://fhircat.org/fhir/contexts/r5/bundle.entry.context.jsonld

**Comment by cendle** [comment]
Fixed issue.  Updated context files are checked into https://github.com/fhircat/jsonld_context_files
